### ISSUE TITLE
 `find_type': unable to resolve type 'uint64_t' (TypeError)

### ISSUE THREAD

**Issue by HoneyryderChuck** [cotag/ruby-tls#12]
I'm getting this error when running ruby-tls in all my docker images:

```
Traceback (most recent call last):
        22: from /usr/env/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `<main>'
        21: from /usr/env/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `select'
        20: from /usr/env/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
        19: from /usr/env/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `require'
        18: from /home/test/cli_test.rb:3:in `<top (required)>'
        17: from /home/test/cli_test.rb:3:in `require_relative'
        16: from /home/test/test_helper.rb:91:in `<top (required)>'
        15: from /home/test/test_helper.rb:91:in `each'
        14: from /home/test/test_helper.rb:91:in `block in <top (required)>'
        13: from /home/test/test_helper.rb:91:in `require'
        12: from /home/test/support/tls_socket.rb:3:in `<top (required)>'
        11: from /home/test/support/tls_socket.rb:3:in `require'
        10: from /usr/env/bundle/ruby/2.5.0/gems/ruby-tls-2.4.0/lib/ruby-tls.rb:3:in `<top (required)>'
         9: from /usr/env/bundle/ruby/2.5.0/gems/ruby-tls-2.4.0/lib/ruby-tls.rb:3:in `require'
         8: from /usr/env/bundle/ruby/2.5.0/gems/ruby-tls-2.4.0/lib/ruby-tls/ssl.rb:9:in `<top (required)>'
         7: from /usr/env/bundle/ruby/2.5.0/gems/ruby-tls-2.4.0/lib/ruby-tls/ssl.rb:10:in `<module:RubyTls>'
         6: from /usr/env/bundle/ruby/2.5.0/gems/ruby-tls-2.4.0/lib/ruby-tls/ssl.rb:36:in `<module:SSL>'
         5: from /usr/env/bundle/ruby/2.5.0/gems/ruby-tls-2.4.0/lib/ruby-tls/ssl.rb:51:in `rescue in <module:SSL>'
         4: from /usr/env/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:241:in `attach_function'
         3: from /usr/env/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:241:in `map'
         2: from /usr/env/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:241:in `block in attach_function'
         1: from /usr/env/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:587:in `find_type'
/usr/env/bundle/ruby/2.5.0/gems/ffi-1.9.23/lib/ffi/types.rb:69:in `find_type': unable to resolve type 'uint64_t' (TypeError)
```

This is on load, so it's nothing I've worked towards.

The system openssl is the following:

```
root@d87b20e4d437:/home# openssl version
OpenSSL 1.1.0f  25 May 2017
```

Is there something in the last minor version that might have caused this issue?

**Comment by HoneyryderChuck** [comment]
I'd say that it should be using `:uint64`, or is it smth else?

**Comment by HoneyryderChuck** [comment]
At least according to [this list](https://github.com/ffi/ffi/wiki/Types) there is no support for such a type.
